# fly.toml file generated for geniuspage on 2023-03-02T20:19:38+01:00

app = "geniuspage"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = '8080'

[experimental]
  auto_rollback = true

[[services]] 
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
    
